### PR TITLE
fix kotlin nullable errors

### PR DESCRIPTION
**Pull request by bdlindsay**
Fixes https://github.com/jachzen/cunning_document_scanner/issues/4

I'm not sure of the context of these changes - so there's still some unsafe stuff going on here, but it at least compiles and would crash only when the original code could crash as well.

### CODE REVIEW

**Comment by bdlindsay** [comment]
I add a couple more commits to update the permission handler dependency to a version that supports android compile SDK version 33 and to bump the version

**Comment by vicajilau** [comment]
Well done, this works for me!

**Comment by kavimproduction** [comment]
> I add a couple more commits to update the permission handler dependency to a version that supports android compile SDK version 33 and to bump the version

Hi, I try all, but it didn't work for me, when you will update the package version on pub? 
Thanks

**Comment by bdlindsay** [comment]
Sorry it didn't work for you, and sorry, I'm not the package maintainer, so I cannot update it on pub.dev. Only [jachzen](https://github.com/jachzen) can merge in this and release it on pub.dev

**Comment by vicajilau** [comment]
As a clarification, after my update of kotlin and gradle in the android compilation I had an error associated with an optional boolean that turned out to be boolean, I had to enter the CunningDocumentScannerPlugin file in the directory [Android Project]/cunning_document_scanner/java/biz.cunning.cunning_document_scanner and remove the optionality of line 112. I took the opportunity to clean some other warnings that the file contained. I hope it's helpful to someone else.

**Comment by jachzen** [comment]
I fixed it in version 1.0.4. Is there still an issue?

**Comment by vicajilau** [comment]
Now works perfectly!! Thank you 👏🏻👏🏻

**Pull request closed without merging**
